### ISSUE TITLE
Truncated glyphs

### ISSUE THREAD

**Issue by kitsunyan** [wareya/ffam#2]
I can't create monospace font since `ffam-build` truncates non-white area of glyph, thus producing proportional font.

https://github.com/wareya/ffam/blob/9a474d64417c20de47f8fbcb333ae27d0612dc17/ffam-build.cpp#L381-L387

I fixed it replacing condition:

```diff
--- a/ffam-build.cpp
+++ b/ffam-build.cpp
@@ -378,7 +378,7 @@ int main(int argc, char ** argv)
         {
             auto rx = i%d;
             auto ry = i/d;
-            if(pixels[x+rx + w*ry] == c_fg)
+            if(pixels[x+rx + w*ry] != c_null)
             {
                 if(rx < minx) minx = rx;
                 if(rx > maxx) maxx = rx;
```

**Comment by wareya** [comment]
Woah, I never thought someone would actually use this.

Yeah, I wasn't considering monospace fonts. If you want, if you make a pull request with a compile-time option or a command line flag, I'll merge it. Glad it was a one-line patch for you to fix it for yourself.

**Comment by kitsunyan** [comment]
I wanted to convert VT font in PSF format to GRUB font in PFF2 format, so VT and GRUB looked similarly. And it seems that I was the first who wanted to do something like that. After some searching I found this tool and it was very helpful, despite the issue! [dsc01297](https://user-images.githubusercontent.com/24494863/39884344-1c830da0-5479-11e8-8c6e-c60214315d84.JPG)

Ok, I'll make a PR with the patch, if you think it's correct.
